/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cc9435d561e3059c6309d1c80ce8629b)
interface __BaseEnv_Env {
  DOWNLOAD_DB: D1Database;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
