/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/events/wrangler.jsonc --include-runtime=false --env-interface=AnalyticsWorkerBindings workers/events/worker-configuration.d.ts` (hash: 81f6792a18d83d567c47b9a872304e01)
interface __BaseEnv_AnalyticsWorkerBindings {
  ANALYTICS_DB: D1Database;
  ANALYTICS_INGESTION_RATE_LIMITER: RateLimit;
  CF_VERSION_METADATA: WorkerVersionMetadata;
  DESKTOP_INGESTION_ENABLED: "true";
  DESKTOP_POSTHOG_EXPORT_ENABLED: "true";
  POSTHOG_PROJECT_ID: "228610";
  POSTHOG_PROJECT_TOKEN: string;
  POSTHOG_PERSONAL_API_KEY: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env extends __BaseEnv_AnalyticsWorkerBindings {}
}
interface AnalyticsWorkerBindings extends __BaseEnv_AnalyticsWorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "DESKTOP_INGESTION_ENABLED"
      | "DESKTOP_POSTHOG_EXPORT_ENABLED"
      | "POSTHOG_PROJECT_ID"
      | "POSTHOG_PROJECT_TOKEN"
      | "POSTHOG_PERSONAL_API_KEY"
    >
  > {}
}
