/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/events/wrangler.jsonc --include-runtime=false --env-interface=AnalyticsWorkerBindings workers/events/worker-configuration.d.ts` (hash: ec6c211557aaf856bf40f03bf0d7023a)
interface __BaseEnv_AnalyticsWorkerBindings {
  ANALYTICS_DB: D1Database;
  ANALYTICS_INGESTION_RATE_LIMITER: RateLimit;
  DESKTOP_INGESTION_ENABLED: "false";
  DESKTOP_POSTHOG_EXPORT_ENABLED: "false";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env extends __BaseEnv_AnalyticsWorkerBindings {}
}
interface AnalyticsWorkerBindings extends __BaseEnv_AnalyticsWorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "DESKTOP_INGESTION_ENABLED" | "DESKTOP_POSTHOG_EXPORT_ENABLED">
  > {}
}
